// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kg_sugg.proto

#ifndef PROTOBUF_kg_5fsugg_2eproto__INCLUDED
#define PROTOBUF_kg_5fsugg_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace kg_sugg {
namespace pb {
class KGSugg;
class KGSuggDefaultTypeInternal;
extern KGSuggDefaultTypeInternal _KGSugg_default_instance_;
class KGSuggs;
class KGSuggsDefaultTypeInternal;
extern KGSuggsDefaultTypeInternal _KGSuggs_default_instance_;
}  // namespace pb
}  // namespace kg_sugg

namespace kg_sugg {
namespace pb {

namespace protobuf_kg_5fsugg_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_kg_5fsugg_2eproto

// ===================================================================

class KGSugg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:kg_sugg.pb.KGSugg) */ {
 public:
  KGSugg();
  virtual ~KGSugg();

  KGSugg(const KGSugg& from);

  inline KGSugg& operator=(const KGSugg& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  KGSugg(KGSugg&& from) noexcept
    : KGSugg() {
    *this = ::std::move(from);
  }

  inline KGSugg& operator=(KGSugg&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const KGSugg& default_instance();

  static inline const KGSugg* internal_default_instance() {
    return reinterpret_cast<const KGSugg*>(
               &_KGSugg_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(KGSugg* other);
  friend void swap(KGSugg& a, KGSugg& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline KGSugg* New() const PROTOBUF_FINAL { return New(NULL); }

  KGSugg* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const KGSugg& from);
  void MergeFrom(const KGSugg& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(KGSugg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string query = 1;
  bool has_query() const;
  void clear_query();
  static const int kQueryFieldNumber = 1;
  const ::std::string& query() const;
  void set_query(const ::std::string& value);
  #if LANG_CXX11
  void set_query(::std::string&& value);
  #endif
  void set_query(const char* value);
  void set_query(const char* value, size_t size);
  ::std::string* mutable_query();
  ::std::string* release_query();
  void set_allocated_query(::std::string* query);

  // optional string query_hl = 2;
  bool has_query_hl() const;
  void clear_query_hl();
  static const int kQueryHlFieldNumber = 2;
  const ::std::string& query_hl() const;
  void set_query_hl(const ::std::string& value);
  #if LANG_CXX11
  void set_query_hl(::std::string&& value);
  #endif
  void set_query_hl(const char* value);
  void set_query_hl(const char* value, size_t size);
  ::std::string* mutable_query_hl();
  ::std::string* release_query_hl();
  void set_allocated_query_hl(::std::string* query_hl);

  // @@protoc_insertion_point(class_scope:kg_sugg.pb.KGSugg)
 private:
  void set_has_query();
  void clear_has_query();
  void set_has_query_hl();
  void clear_has_query_hl();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr query_;
  ::google::protobuf::internal::ArenaStringPtr query_hl_;
  friend struct protobuf_kg_5fsugg_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class KGSuggs : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:kg_sugg.pb.KGSuggs) */ {
 public:
  KGSuggs();
  virtual ~KGSuggs();

  KGSuggs(const KGSuggs& from);

  inline KGSuggs& operator=(const KGSuggs& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  KGSuggs(KGSuggs&& from) noexcept
    : KGSuggs() {
    *this = ::std::move(from);
  }

  inline KGSuggs& operator=(KGSuggs&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const KGSuggs& default_instance();

  static inline const KGSuggs* internal_default_instance() {
    return reinterpret_cast<const KGSuggs*>(
               &_KGSuggs_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(KGSuggs* other);
  friend void swap(KGSuggs& a, KGSuggs& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline KGSuggs* New() const PROTOBUF_FINAL { return New(NULL); }

  KGSuggs* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const KGSuggs& from);
  void MergeFrom(const KGSuggs& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(KGSuggs* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .kg_sugg.pb.KGSugg suggs = 1;
  int suggs_size() const;
  void clear_suggs();
  static const int kSuggsFieldNumber = 1;
  const ::kg_sugg::pb::KGSugg& suggs(int index) const;
  ::kg_sugg::pb::KGSugg* mutable_suggs(int index);
  ::kg_sugg::pb::KGSugg* add_suggs();
  ::google::protobuf::RepeatedPtrField< ::kg_sugg::pb::KGSugg >*
      mutable_suggs();
  const ::google::protobuf::RepeatedPtrField< ::kg_sugg::pb::KGSugg >&
      suggs() const;

  // @@protoc_insertion_point(class_scope:kg_sugg.pb.KGSuggs)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::kg_sugg::pb::KGSugg > suggs_;
  friend struct protobuf_kg_5fsugg_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// KGSugg

// optional string query = 1;
inline bool KGSugg::has_query() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void KGSugg::set_has_query() {
  _has_bits_[0] |= 0x00000001u;
}
inline void KGSugg::clear_has_query() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void KGSugg::clear_query() {
  query_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_query();
}
inline const ::std::string& KGSugg::query() const {
  // @@protoc_insertion_point(field_get:kg_sugg.pb.KGSugg.query)
  return query_.GetNoArena();
}
inline void KGSugg::set_query(const ::std::string& value) {
  set_has_query();
  query_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:kg_sugg.pb.KGSugg.query)
}
#if LANG_CXX11
inline void KGSugg::set_query(::std::string&& value) {
  set_has_query();
  query_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:kg_sugg.pb.KGSugg.query)
}
#endif
inline void KGSugg::set_query(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_query();
  query_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:kg_sugg.pb.KGSugg.query)
}
inline void KGSugg::set_query(const char* value, size_t size) {
  set_has_query();
  query_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:kg_sugg.pb.KGSugg.query)
}
inline ::std::string* KGSugg::mutable_query() {
  set_has_query();
  // @@protoc_insertion_point(field_mutable:kg_sugg.pb.KGSugg.query)
  return query_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* KGSugg::release_query() {
  // @@protoc_insertion_point(field_release:kg_sugg.pb.KGSugg.query)
  clear_has_query();
  return query_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void KGSugg::set_allocated_query(::std::string* query) {
  if (query != NULL) {
    set_has_query();
  } else {
    clear_has_query();
  }
  query_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), query);
  // @@protoc_insertion_point(field_set_allocated:kg_sugg.pb.KGSugg.query)
}

// optional string query_hl = 2;
inline bool KGSugg::has_query_hl() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void KGSugg::set_has_query_hl() {
  _has_bits_[0] |= 0x00000002u;
}
inline void KGSugg::clear_has_query_hl() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void KGSugg::clear_query_hl() {
  query_hl_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_query_hl();
}
inline const ::std::string& KGSugg::query_hl() const {
  // @@protoc_insertion_point(field_get:kg_sugg.pb.KGSugg.query_hl)
  return query_hl_.GetNoArena();
}
inline void KGSugg::set_query_hl(const ::std::string& value) {
  set_has_query_hl();
  query_hl_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:kg_sugg.pb.KGSugg.query_hl)
}
#if LANG_CXX11
inline void KGSugg::set_query_hl(::std::string&& value) {
  set_has_query_hl();
  query_hl_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:kg_sugg.pb.KGSugg.query_hl)
}
#endif
inline void KGSugg::set_query_hl(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_query_hl();
  query_hl_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:kg_sugg.pb.KGSugg.query_hl)
}
inline void KGSugg::set_query_hl(const char* value, size_t size) {
  set_has_query_hl();
  query_hl_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:kg_sugg.pb.KGSugg.query_hl)
}
inline ::std::string* KGSugg::mutable_query_hl() {
  set_has_query_hl();
  // @@protoc_insertion_point(field_mutable:kg_sugg.pb.KGSugg.query_hl)
  return query_hl_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* KGSugg::release_query_hl() {
  // @@protoc_insertion_point(field_release:kg_sugg.pb.KGSugg.query_hl)
  clear_has_query_hl();
  return query_hl_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void KGSugg::set_allocated_query_hl(::std::string* query_hl) {
  if (query_hl != NULL) {
    set_has_query_hl();
  } else {
    clear_has_query_hl();
  }
  query_hl_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), query_hl);
  // @@protoc_insertion_point(field_set_allocated:kg_sugg.pb.KGSugg.query_hl)
}

// -------------------------------------------------------------------

// KGSuggs

// repeated .kg_sugg.pb.KGSugg suggs = 1;
inline int KGSuggs::suggs_size() const {
  return suggs_.size();
}
inline void KGSuggs::clear_suggs() {
  suggs_.Clear();
}
inline const ::kg_sugg::pb::KGSugg& KGSuggs::suggs(int index) const {
  // @@protoc_insertion_point(field_get:kg_sugg.pb.KGSuggs.suggs)
  return suggs_.Get(index);
}
inline ::kg_sugg::pb::KGSugg* KGSuggs::mutable_suggs(int index) {
  // @@protoc_insertion_point(field_mutable:kg_sugg.pb.KGSuggs.suggs)
  return suggs_.Mutable(index);
}
inline ::kg_sugg::pb::KGSugg* KGSuggs::add_suggs() {
  // @@protoc_insertion_point(field_add:kg_sugg.pb.KGSuggs.suggs)
  return suggs_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::kg_sugg::pb::KGSugg >*
KGSuggs::mutable_suggs() {
  // @@protoc_insertion_point(field_mutable_list:kg_sugg.pb.KGSuggs.suggs)
  return &suggs_;
}
inline const ::google::protobuf::RepeatedPtrField< ::kg_sugg::pb::KGSugg >&
KGSuggs::suggs() const {
  // @@protoc_insertion_point(field_list:kg_sugg.pb.KGSuggs.suggs)
  return suggs_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace pb
}  // namespace kg_sugg

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_kg_5fsugg_2eproto__INCLUDED
