# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmo_domain_docs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cosmo_domain_docs.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x17\x63osmo_domain_docs.proto\"O\n\x15ProtoDomainDocsRecord\x12\x0e\n\x06\x64omain\x18\x01 \x02(\x03\x12&\n\x07\x65ntries\x18\x02 \x03(\x0b\x32\x15.ProtoDomainDocsEntry\"9\n\x14ProtoDomainDocsEntry\x12\x11\n\tsource_id\x18\x01 \x02(\x03\x12\x0e\n\x06\x64oc_id\x18\x02 \x02(\x03')
)




_PROTODOMAINDOCSRECORD = _descriptor.Descriptor(
  name='ProtoDomainDocsRecord',
  full_name='ProtoDomainDocsRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='domain', full_name='ProtoDomainDocsRecord.domain', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='entries', full_name='ProtoDomainDocsRecord.entries', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=106,
)


_PROTODOMAINDOCSENTRY = _descriptor.Descriptor(
  name='ProtoDomainDocsEntry',
  full_name='ProtoDomainDocsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='source_id', full_name='ProtoDomainDocsEntry.source_id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='doc_id', full_name='ProtoDomainDocsEntry.doc_id', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=165,
)

_PROTODOMAINDOCSRECORD.fields_by_name['entries'].message_type = _PROTODOMAINDOCSENTRY
DESCRIPTOR.message_types_by_name['ProtoDomainDocsRecord'] = _PROTODOMAINDOCSRECORD
DESCRIPTOR.message_types_by_name['ProtoDomainDocsEntry'] = _PROTODOMAINDOCSENTRY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProtoDomainDocsRecord = _reflection.GeneratedProtocolMessageType('ProtoDomainDocsRecord', (_message.Message,), dict(
  DESCRIPTOR = _PROTODOMAINDOCSRECORD,
  __module__ = 'cosmo_domain_docs_pb2'
  # @@protoc_insertion_point(class_scope:ProtoDomainDocsRecord)
  ))
_sym_db.RegisterMessage(ProtoDomainDocsRecord)

ProtoDomainDocsEntry = _reflection.GeneratedProtocolMessageType('ProtoDomainDocsEntry', (_message.Message,), dict(
  DESCRIPTOR = _PROTODOMAINDOCSENTRY,
  __module__ = 'cosmo_domain_docs_pb2'
  # @@protoc_insertion_point(class_scope:ProtoDomainDocsEntry)
  ))
_sym_db.RegisterMessage(ProtoDomainDocsEntry)


# @@protoc_insertion_point(module_scope)
