# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: music-playlists.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='music-playlists.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x15music-playlists.proto\"z\n\x05Track\x12\x13\n\x0buser_id_old\x18\x01 \x01(\r\x12\x10\n\x08track_id\x18\x02 \x02(\t\x12\x10\n\x08\x64uration\x18\x03 \x02(\r\x12\x12\n\ntrack_name\x18\x04 \x02(\t\x12\x13\n\x0b\x61uthor_name\x18\x05 \x02(\t\x12\x0f\n\x07user_id\x18\x06 \x01(\x04\"7\n\tTrackList\x12\x16\n\x06tracks\x18\x01 \x03(\x0b\x32\x06.Track\x12\x12\n\nlisten_key\x18\x02 \x02(\t')
)




_TRACK = _descriptor.Descriptor(
  name='Track',
  full_name='Track',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id_old', full_name='Track.user_id_old', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='track_id', full_name='Track.track_id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='duration', full_name='Track.duration', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='track_name', full_name='Track.track_name', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='author_name', full_name='Track.author_name', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='Track.user_id', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=147,
)


_TRACKLIST = _descriptor.Descriptor(
  name='TrackList',
  full_name='TrackList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tracks', full_name='TrackList.tracks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='listen_key', full_name='TrackList.listen_key', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=204,
)

_TRACKLIST.fields_by_name['tracks'].message_type = _TRACK
DESCRIPTOR.message_types_by_name['Track'] = _TRACK
DESCRIPTOR.message_types_by_name['TrackList'] = _TRACKLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Track = _reflection.GeneratedProtocolMessageType('Track', (_message.Message,), dict(
  DESCRIPTOR = _TRACK,
  __module__ = 'music_playlists_pb2'
  # @@protoc_insertion_point(class_scope:Track)
  ))
_sym_db.RegisterMessage(Track)

TrackList = _reflection.GeneratedProtocolMessageType('TrackList', (_message.Message,), dict(
  DESCRIPTOR = _TRACKLIST,
  __module__ = 'music_playlists_pb2'
  # @@protoc_insertion_point(class_scope:TrackList)
  ))
_sym_db.RegisterMessage(TrackList)


# @@protoc_insertion_point(module_scope)
