# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sugg_db.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import suggests_pb2 as suggests__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sugg_db.proto',
  package='ru.mail.go.sugg.indexer',
  syntax='proto2',
  serialized_pb=_b('\n\rsugg_db.proto\x12\x17ru.mail.go.sugg.indexer\x1a\x0esuggests.proto\"n\n\x0eSuggInfoRecord\x12\r\n\x05query\x18\x01 \x01(\t\x12\x12\n\nporno_prob\x18\x02 \x01(\x01\x12\x39\n\x08site_res\x18\x03 \x01(\x0b\x32\'.ru.mail.go.sugg.indexer.SuggSiteResult')
  ,
  dependencies=[suggests__pb2.DESCRIPTOR,])




_SUGGINFORECORD = _descriptor.Descriptor(
  name='SuggInfoRecord',
  full_name='ru.mail.go.sugg.indexer.SuggInfoRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='ru.mail.go.sugg.indexer.SuggInfoRecord.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='porno_prob', full_name='ru.mail.go.sugg.indexer.SuggInfoRecord.porno_prob', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='site_res', full_name='ru.mail.go.sugg.indexer.SuggInfoRecord.site_res', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=168,
)

_SUGGINFORECORD.fields_by_name['site_res'].message_type = suggests__pb2._SUGGSITERESULT
DESCRIPTOR.message_types_by_name['SuggInfoRecord'] = _SUGGINFORECORD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SuggInfoRecord = _reflection.GeneratedProtocolMessageType('SuggInfoRecord', (_message.Message,), dict(
  DESCRIPTOR = _SUGGINFORECORD,
  __module__ = 'sugg_db_pb2'
  # @@protoc_insertion_point(class_scope:ru.mail.go.sugg.indexer.SuggInfoRecord)
  ))
_sym_db.RegisterMessage(SuggInfoRecord)


# @@protoc_insertion_point(module_scope)
