# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vk_reco.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import document_enums_pb2 as document__enums__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='vk_reco.proto',
  package='ru.mail.go.webbase.blobs',
  syntax='proto2',
  serialized_pb=_b('\n\rvk_reco.proto\x12\x18ru.mail.go.webbase.blobs\x1a\x14\x64ocument_enums.proto\"\x89\x01\n\x0fVkRecoContainer\x12\x34\n\x06\x63ommon\x18\x01 \x03(\x0b\x32$.ru.mail.go.webbase.blobs.VkRecoItem\x12@\n\x12highly_recommended\x18\x02 \x03(\x0b\x32$.ru.mail.go.webbase.blobs.VkRecoItem\"\x87\x01\n\nVkRecoItem\x12\x0f\n\x07user_id\x18\x01 \x02(\x03\x12\x0f\n\x07item_id\x18\x02 \x02(\x03\x12\x17\n\x0fnum_encountered\x18\x03 \x01(\x03\x12>\n\x08metadata\x18\x04 \x01(\x0b\x32,.ru.mail.go.webbase.blobs.VkRecoItemMetadata\"K\n\x12VkRecoItemMetadata\x12\x10\n\x08\x64uration\x18\x01 \x01(\x05\x12\x11\n\tstatViews\x18\x02 \x01(\x03\x12\x10\n\x08official\x18\x03 \x01(\x08\x42\x08\x42\x06VkReco')
  ,
  dependencies=[document__enums__pb2.DESCRIPTOR,])




_VKRECOCONTAINER = _descriptor.Descriptor(
  name='VkRecoContainer',
  full_name='ru.mail.go.webbase.blobs.VkRecoContainer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='common', full_name='ru.mail.go.webbase.blobs.VkRecoContainer.common', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='highly_recommended', full_name='ru.mail.go.webbase.blobs.VkRecoContainer.highly_recommended', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=203,
)


_VKRECOITEM = _descriptor.Descriptor(
  name='VkRecoItem',
  full_name='ru.mail.go.webbase.blobs.VkRecoItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='ru.mail.go.webbase.blobs.VkRecoItem.user_id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='item_id', full_name='ru.mail.go.webbase.blobs.VkRecoItem.item_id', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_encountered', full_name='ru.mail.go.webbase.blobs.VkRecoItem.num_encountered', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='ru.mail.go.webbase.blobs.VkRecoItem.metadata', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=341,
)


_VKRECOITEMMETADATA = _descriptor.Descriptor(
  name='VkRecoItemMetadata',
  full_name='ru.mail.go.webbase.blobs.VkRecoItemMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='duration', full_name='ru.mail.go.webbase.blobs.VkRecoItemMetadata.duration', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='statViews', full_name='ru.mail.go.webbase.blobs.VkRecoItemMetadata.statViews', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='official', full_name='ru.mail.go.webbase.blobs.VkRecoItemMetadata.official', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=343,
  serialized_end=418,
)

_VKRECOCONTAINER.fields_by_name['common'].message_type = _VKRECOITEM
_VKRECOCONTAINER.fields_by_name['highly_recommended'].message_type = _VKRECOITEM
_VKRECOITEM.fields_by_name['metadata'].message_type = _VKRECOITEMMETADATA
DESCRIPTOR.message_types_by_name['VkRecoContainer'] = _VKRECOCONTAINER
DESCRIPTOR.message_types_by_name['VkRecoItem'] = _VKRECOITEM
DESCRIPTOR.message_types_by_name['VkRecoItemMetadata'] = _VKRECOITEMMETADATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VkRecoContainer = _reflection.GeneratedProtocolMessageType('VkRecoContainer', (_message.Message,), dict(
  DESCRIPTOR = _VKRECOCONTAINER,
  __module__ = 'vk_reco_pb2'
  # @@protoc_insertion_point(class_scope:ru.mail.go.webbase.blobs.VkRecoContainer)
  ))
_sym_db.RegisterMessage(VkRecoContainer)

VkRecoItem = _reflection.GeneratedProtocolMessageType('VkRecoItem', (_message.Message,), dict(
  DESCRIPTOR = _VKRECOITEM,
  __module__ = 'vk_reco_pb2'
  # @@protoc_insertion_point(class_scope:ru.mail.go.webbase.blobs.VkRecoItem)
  ))
_sym_db.RegisterMessage(VkRecoItem)

VkRecoItemMetadata = _reflection.GeneratedProtocolMessageType('VkRecoItemMetadata', (_message.Message,), dict(
  DESCRIPTOR = _VKRECOITEMMETADATA,
  __module__ = 'vk_reco_pb2'
  # @@protoc_insertion_point(class_scope:ru.mail.go.webbase.blobs.VkRecoItemMetadata)
  ))
_sym_db.RegisterMessage(VkRecoItemMetadata)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('B\006VkReco'))
# @@protoc_insertion_point(module_scope)
