# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: youla_paid_ad.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='youla_paid_ad.proto',
  package='youla.paidad.pb',
  syntax='proto2',
  serialized_pb=_b('\n\x13youla_paid_ad.proto\x12\x0fyoula.paidad.pb\",\n\x08ViewInfo\x12\x12\n\nproduct_id\x18\x01 \x02(\t\x12\x0c\n\x04time\x18\x02 \x01(\x04\"?\n\x0fPaidAdUserViews\x12,\n\tview_info\x18\x01 \x03(\x0b\x32\x19.youla.paidad.pb.ViewInfoB\rB\x0bYoulaPaidAd')
)




_VIEWINFO = _descriptor.Descriptor(
  name='ViewInfo',
  full_name='youla.paidad.pb.ViewInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='product_id', full_name='youla.paidad.pb.ViewInfo.product_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='youla.paidad.pb.ViewInfo.time', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=84,
)


_PAIDADUSERVIEWS = _descriptor.Descriptor(
  name='PaidAdUserViews',
  full_name='youla.paidad.pb.PaidAdUserViews',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='view_info', full_name='youla.paidad.pb.PaidAdUserViews.view_info', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=149,
)

_PAIDADUSERVIEWS.fields_by_name['view_info'].message_type = _VIEWINFO
DESCRIPTOR.message_types_by_name['ViewInfo'] = _VIEWINFO
DESCRIPTOR.message_types_by_name['PaidAdUserViews'] = _PAIDADUSERVIEWS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ViewInfo = _reflection.GeneratedProtocolMessageType('ViewInfo', (_message.Message,), dict(
  DESCRIPTOR = _VIEWINFO,
  __module__ = 'youla_paid_ad_pb2'
  # @@protoc_insertion_point(class_scope:youla.paidad.pb.ViewInfo)
  ))
_sym_db.RegisterMessage(ViewInfo)

PaidAdUserViews = _reflection.GeneratedProtocolMessageType('PaidAdUserViews', (_message.Message,), dict(
  DESCRIPTOR = _PAIDADUSERVIEWS,
  __module__ = 'youla_paid_ad_pb2'
  # @@protoc_insertion_point(class_scope:youla.paidad.pb.PaidAdUserViews)
  ))
_sym_db.RegisterMessage(PaidAdUserViews)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('B\013YoulaPaidAd'))
# @@protoc_insertion_point(module_scope)
