# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: youla_embed_recom.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='youla_embed_recom.proto',
  package='youla.embed_recom.pb',
  syntax='proto2',
  serialized_pb=_b('\n\x17youla_embed_recom.proto\x12\x14youla.embed_recom.pb\"\x1f\n\tEmbedding\x12\x12\n\ncomponents\x18\x01 \x03(\x02\"1\n\x0cSubcatWeight\x12\x11\n\tsubcat_id\x18\x01 \x02(\r\x12\x0e\n\x06weight\x18\x02 \x02(\x02\"D\n\rSubcatWeights\x12\x33\n\x07weights\x18\x01 \x03(\x0b\x32\".youla.embed_recom.pb.SubcatWeight')
)




_EMBEDDING = _descriptor.Descriptor(
  name='Embedding',
  full_name='youla.embed_recom.pb.Embedding',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='components', full_name='youla.embed_recom.pb.Embedding.components', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=80,
)


_SUBCATWEIGHT = _descriptor.Descriptor(
  name='SubcatWeight',
  full_name='youla.embed_recom.pb.SubcatWeight',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subcat_id', full_name='youla.embed_recom.pb.SubcatWeight.subcat_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='weight', full_name='youla.embed_recom.pb.SubcatWeight.weight', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=131,
)


_SUBCATWEIGHTS = _descriptor.Descriptor(
  name='SubcatWeights',
  full_name='youla.embed_recom.pb.SubcatWeights',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='weights', full_name='youla.embed_recom.pb.SubcatWeights.weights', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=201,
)

_SUBCATWEIGHTS.fields_by_name['weights'].message_type = _SUBCATWEIGHT
DESCRIPTOR.message_types_by_name['Embedding'] = _EMBEDDING
DESCRIPTOR.message_types_by_name['SubcatWeight'] = _SUBCATWEIGHT
DESCRIPTOR.message_types_by_name['SubcatWeights'] = _SUBCATWEIGHTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Embedding = _reflection.GeneratedProtocolMessageType('Embedding', (_message.Message,), dict(
  DESCRIPTOR = _EMBEDDING,
  __module__ = 'youla_embed_recom_pb2'
  # @@protoc_insertion_point(class_scope:youla.embed_recom.pb.Embedding)
  ))
_sym_db.RegisterMessage(Embedding)

SubcatWeight = _reflection.GeneratedProtocolMessageType('SubcatWeight', (_message.Message,), dict(
  DESCRIPTOR = _SUBCATWEIGHT,
  __module__ = 'youla_embed_recom_pb2'
  # @@protoc_insertion_point(class_scope:youla.embed_recom.pb.SubcatWeight)
  ))
_sym_db.RegisterMessage(SubcatWeight)

SubcatWeights = _reflection.GeneratedProtocolMessageType('SubcatWeights', (_message.Message,), dict(
  DESCRIPTOR = _SUBCATWEIGHTS,
  __module__ = 'youla_embed_recom_pb2'
  # @@protoc_insertion_point(class_scope:youla.embed_recom.pb.SubcatWeights)
  ))
_sym_db.RegisterMessage(SubcatWeights)


# @@protoc_insertion_point(module_scope)
